---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  yaml: ./tasks/yaml.yml

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task --list

  clean:
    desc: Clean the project
    silent: true
    deps: []
    cmds: []

  build:
    desc: Build the project
    silent: true
    deps: []
    cmds: []

  test:
    desc: Test the project
    silent: true
    deps: []
    cmds: []

  lint:
    desc: Check for linting/formatting errors
    silent: true
    deps:
      - yaml:lint
    cmds: []

  fix:
    desc: Fix linting/formatting errors
    silent: true
    deps:
      - yaml:fix
    cmds: []
