---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  yaml: ./tasks/yaml.yml
  toml: ./tasks/toml.yml
  rust: ./tasks/rust.yml

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task --list

  clean:
    desc: Clean the project
    silent: true
    deps:
      - rust:clean
    cmds: []

  build:
    desc: Build the project
    silent: true
    deps:
      - rust:build
    cmds: []

  test:
    desc: Test the project
    silent: true
    deps:
      - rust:test
    cmds: []

  lint:
    desc: Check for linting/formatting errors
    silent: true
    deps:
      - yaml:lint
      - toml:lint
      - rust:lint
    cmds: []

  fix:
    desc: Fix linting/formatting errors
    silent: true
    deps:
      - yaml:fix
      - toml:fix
      - rust:fix
    cmds: []
