---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  yaml: ./tasks/yaml.yml
  c: ./tasks/c.yml

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task --list

  clean:
    desc: Clean the project
    silent: true
    deps:
      - c:clean
    cmds: []

  build:
    desc: Build the project
    silent: true
    deps:
      - c:build
    cmds: []

  test:
    desc: Test the project
    silent: true
    deps:
      - c:test
    cmds: []

  check:
    desc: Check for linting/formatting errors
    silent: true
    deps:
      - yaml:check
      - c:check
    cmds: []

  format:
    desc: Fix linting/formatting errors
    silent: true
    aliases:
      - fmt
    deps:
      - yaml:format
      - c:format
    cmds: []
