---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  yaml: ./tasks/yaml.yml
  python: ./tasks/python.yml

tasks:
  default:
    desc: List tasks
    silent: true
    cmds:
      - task --list

  clean:
    desc: Clean the project
    silent: true
    deps:
      - python:clean
    cmds: []

  build:
    desc: Build the project
    silent: true
    deps:
      - python:build
    cmds: []

  test:
    desc: Test the project
    silent: true
    deps:
      - python:test
    cmds: []

  check:
    desc: Check for linting/formatting errors
    silent: true
    deps:
      - yaml:check
      - python:check
    cmds: []

  fix:
    desc: Fix linting/formatting errors
    silent: true
    deps:
      - yaml:fix
      - python:fix
    cmds: []
